NOTAM_TYPES = {
    "N": "new",
    "R": "replacement",
}

NOTAM_SCOPES = {
    "A": "aerodrome",
    "E": "enroute",
    "W": "nav_warning",
}

NOTAM_TRAFFIC = {
    "I": "IFR (Instrument Flight Rules)",
    "V": "VFR (Visual Flight Rules)",
}

NOTAM_PURPOSES = {
    "N": "For immediate attention of aircraft operators",
    "B": "For PIB entry",
    "O": "Concerning Flight operations",
    "M": "Miscellaneous",
}

# FIXME: Are these all correct for the UK?
# We may need to get every version of this table historically and ensure we are using the correct version for each notam based on the publish date
# How do we know when this changes?
NOTAM_SERIES = {
    "A": "Licensed Aerodromes within the London FIR",
    "B": "En-route Airspace London FIR/UIR & Scottish FIR/UIR",
    "C": "Licensed Aerodromes within the London FIR and Channel Islands",
    "D": "Special Use Airspace within ENR 5.1 and ENR 5.2",
    "E": "Unlicensed Aerodromes within the London FIR and Scottish FIR for the notification of safety related subjects relating to facilities and services",
    "F": "FIXME: What is this?!",  # FIXME
    "G": "En-route Airspace Shanwick Oceanic FIR: Regulations & Procedures, ATS, Air/Ground",
    "C": "unications, Special Use Airspace within ENR 5.1 and ENR 5.2, and Navigation Warnings",
    "H": "Navigation Warnings Jan to Jun",
    "I": "Licensed Aerodromes within the Scottish FIR",
    "J": "Temporary Danger Areas (TDA) and Restricted Areas (Temporary)",
    "K": "Navigation Warnings Jul to Dec",
    "L": "Licensed Aerodromes within the London FIR",
    "M": "AMC Managed Special Use Airspace within ENR 5.1 and ENR 5.2 including relevant military exercises",
    "N": "En-route obstacles and lights above 100 M (328 FT) AGL and En-route Obstacles and lights below 100 M (328 FT) AGL within the UK Military Low Flying System",
    "P": "FIXME: What is this?!", # FIXME
    "Q": "FIXME: What is this?!", # FIXME
    "R": "FIXME: What is this?!",  # FIXME
    "U": "UK Military Aerodromes, UK Sovereign Bases and Overseas Territories",
    "V": "Notification of Security Advice to UK Air Operators by Government to provide guidance/instructions on airspace security risks. Volcanic Ash related information within En-Route Airspace",
    "X": "Contingency: Applied in event of unplanned, long-term outage of normal NOTAM production system",
}

NOTAM_CONDITIONS = {
    "AD": "AVAILABLE FOR DAY OPERATION",
    "CR": "TEMPORARILY REPLACED BY",
    "AG": "OPERATING, AWAITING FLIGHT CHECK",
    "CS": "INSTALLED",
    "AH": "HOURS OF OPS/SERVICE",
    "CT": "ON TEST DO NOT USE",
    "AK": "RESUMED NORMAL OPERATIONS",
    "HG": "GRASS CUTTING",
    "AL": "OPERATING SUBJECT TO PREVIOUS CONDITION",
    "HW": "WORK IN PROGRESS",
    "AM": "MILITARY OPERATIONS ONLY",
    "HX": "BIRD CONCENTRATION",
    "AN": "AVAILABLE FOR NIGHT OPERATION",
    "LB": "RESERVED FOR AIRCRAFT BASED",
    "AO": "OPERATIONAL",
    "LC": "CLOSED",
    "AP": "AVAILABLE PPR",
    "LF": "INTERFERENCE",
    "AR": "AVAILABLE ON REQUEST",
    "LG": "OPERATING WITHOUT IDENTIFICATION",
    "AS": "OUT OF SERVICE",
    "LH": "OUT OF SERVICE AIRCRAFT HEAVIER",
    "AU": "NOT AVAILABLE",
    "LI": "CLOSED TO IFR OPERATIONS",
    "AW": "COMPLETELY WITHDRAWN",
    "LL": "USEABLE LENGTH/WIDTH",
    "CA": "ACTIVATED",
    "LN": "CLOSED TO NIGHT OPERATIONS",
    "CC": "COMPLETED",
    "LP": "PROHIBITED",
    "CD": "DEACTIVATED",
    "LR": "AIRCRAFT RESTRICTED TO RWY/TWY",
    "CE": "ERECTED",
    "LS": "SUBJECT TO INTERRUPTION",
    "CF": "FREQUENCY CHANGED",
    "LT": "LIMITED",
    "CG": "DOWNGRADED TO",
    "LV": "CLOSED TO VFR OPERATIONS",
    "CH": "CHANGED",
    "LW": "WILL TAKE PLACE",
    "CI": "IDENTIFICATION/CALLSIGN CHANGED",
    "LX": "CAUTION",
    "CL": "RE-ALIGNED",
    "TT": "TRIGGER NOTAM",
    "CM": "DISPLACED",
    "XX": "ADD AN OBJECTIVE FOR 'XX'",
}


# From Q-Codes-for-Website-DEC-2024.docx
NOTAM_SUBJECT_CATEGORIES = {
    "FACILITIES": {
        "FA": "AERODROME",
        "FB": "FRICTION MEARUREMENT DEVICE (MU METER)",
        "FC": "CEILING MEASUREMENT EQUIPMENT",
        "FD": "DOCKING SYSTEM",
        "FE": "OXYGEN",
        "FF": "FIRE AND RESCUE (RFFS)",
        "FG": "GROUND MOVEMENT CONTROL",
        "FH": "HELICOPTER ALIGHTING AREA",
        "FI": "AIRCRAFT DE-ICING",
        "FL": "LANDING DIRECTION INDICTOR",
        "FJ": "OILS",
        "FM": "MET",
        "FO": "FOG DISPERSAL SYSTEM",
        "FP": "HELIPORT & HELI LANDING SITE (HLS)",
        "FS": "SNOW REMOVAL EQUIPMENT",
        "FT": "TRANSMISSOMETER (RVR)",
        "FU": "FUEL",
        "FW": "WIND DIRECTION INDICATOR (WINDSOCK)",
        "FZ": "CUSTOMS/IMMIGRATION",
    },
    "MOVEMENT AND LANDING AREA": {
        "MA": "MOVEMENT AREA",
        "MB": "BEARING STRENGTH",
        "MC": "CLEARWAY",
        "MD": "DECLARED DISTANCES (TORA, TODA, ASDA, LDA)",
        "MG": "TAXIING GUIDANCE SYSTEM (AGNIS)",
        "MH": "RUNWAY ARRESTING GEAR (BARRIERS & CABLES)",
        "MK": "PARKING AREA (ORP, ASP, RAMP, HAS, PAS, BAY)",
        "MM": "DAYLIGHT MARKINGS",
        "MN": "APRON",
        "MO": "STOPBAR",
        "MP": "AIRCRAFT STAND & HARD STAND",
        "MR": "RUNWAY",
        "MS": "STOPWAY",
        "MT": "THRESHOLD",
        "MU": "RUNWAY TURNING BAY",
        "MW": "STRIP/SHOULDER",
        "MX": "TAXIWAY",
        "MY": "RAPID EXIT TAXIWAY",
    },
    "LIGHTING FACILITIES": {
        "LA": "APPROACH LIGHT SYSTEM",
        "LB": "AERODROME BEACON",
        "LC": "RUNWAY CENTRELINE LIGHTS",
        "LD": "LANDING DIRECTION INDICATOR LIGHTS",
        "LE": "RUNWAY EDGE LIGHTS",
        "LF": "SEQUENCE FLASHING LIGHTS",
        "LG": "PILOT CONTROLLED LIGHTING",
        "LH": "RUNWAY LIGHT INTENSITY HIGH",
        "LI": "RUNWAY END IDENTIFIER LIGHTS",
        "LJ": "RUNWAY ALIGNMENT IDENTIFIER LIGHTS",
        "LK": "ILS CAT 2 COMPONENT APPROACH LIGHTS",
        "LL": "RUNWAY LIGHT INTENSITY LOW",
        "LM": "RUNWAY LIGHT INTENSITY MEDIUM",
        "LP": "PAPI & APAPI",
        "LR": "ALL LANDING AREA LIGHT FACILITIES",
        "LS": "STOPWAY LIGHTS",
        "LT": "THRESHOLD LIGHTS",
        "LU": "HELICOPTER APPROACH PATH INDICATOR",
        "LV": "VASIS",
        "LW": "HELIPORT LIGHTS",
        "LX": "TAXIWAY CENTRELINE LIGHTS",
        "LY": "TAXIWAY EDGE LIGHTS",
        "LZ": "TOUCHDOWN ZONE LIGHTS",
    },
    "COMMUNICATIONS AND RADAR FACILITIES": {
        "CA": "AIR TO GROUND FACILITY (FREQUENCY)",
        "CB": "ADS - BROADCAST",
        "CC": "ADS - CONTRACT",
        "CD": "CONTROLLER PILOT DATA LINK COM (CPDLC)",
        "CE": "EN ROUTE SURVEILLANCE RADAR (RSR)",
        "CG": "GROUND CONTROLLED APPROACH SYSTEM",
        "CL": "SELECTIVE CALLING SYSTEM (SELCAL)",
        "CM": "SURFACE MOVEMENT RADAR",
        "CP": "PRECISION APPROACH RADAR (PAR)",
        "CR": "SURVEILLANCE RADAR ELEMENT OF PAR (SRE)",
        "CS": "SECONDARY SURVEILLANCE RADAR (SSR)",
        "CT": "TERMINAL AREA SURVEILLANCE RADAR (TAR)",
    },
    "INSTRUMENT AND MICROWAVE LANDING SYSTEMS": {
        "IC": "ILS",
        "ID": "DME ASSOCIATED WITH ILS",
        "IG": "ILS GLIDE PATH",
        "II": "ILS INNER MARKER",
        "IL": "ILS LOCALIZER",
        "IM": "ILS MIDDLE MARKER",
        "IN": "LOCALIZER",
        "IO": "ILS OUTER MARKER",
        "IS": "ILS CAT 1",
        "IT": "ILS CAT 2",
        "IU": "ILS CAT 3",
        "IW": "MICROWAVE LANDING SYSTEM (MLS)",
        "IX": "ILS LOCATOR OUTER",
        "IY": "ILS LOCATOR MIDDLE",
    },
    "GLOBAL NAVIGATION SATELLITE SYSTEM	": {
        "GA": "GNSS AD SPECIFIC OPS (GPS JAMMING)",
        "GW": "GNSS AREA WIDE OPS (GPS JAMMING)",
    },
    "NAVIGATION FACILITIES": {
        "NA": "ALL RADIO NAVIGATION FACILITIES EXCEPT",
        "NB": "NDB",
        "ND": "DME",
        "NF": "FAN MARKER",
        "NL": "LOCATOR & NDB (L)",
        "NM": "VOR/DME",
        "NN": "TACAN",
        "NT": "VOR TACAN (VORTAC)",
        "NV": "VOR",
        "NX": "DIRECTION FINDING STATION (DF & VDF)",
    },
    "AIRSPACE ORGANISATION": {
        "AA": "MINIMUM ALTITUDE",
        "AC": "CTR",
        "AD": "AIR DEFENCE INDITIFCATION ZONE (ADIZ)",
        "AE": "CTA",
        "AF": "FIR",
        "AH": "UPPER CONTROL AREA (UTA)",
        "AL": "MINIMUM USEABLE FL",
        "AN": "RNAV ROUTE",
        "AO": "OCEANIC CONTROL AREA",
        "AP": "REPORTING POINT",
        "AR": "ATS ROUTE",
        "AT": "TMA",
        "AU": "UIR",
        "AV": "UPPER ADVISORY AREA (UDA)",
        "AX": "SIGNIFICANT POINT",
        "AZ": "ATZ, MATZ & RMZ",
    },
    "PROCEDURES": {
        "PA": "STAR",
        "PB": "STANDARD VFR ARRIVAL",
        "PC": "CONTINGENCY PROCEDURES",
        "PD": "SID",
        "PE": "STANDARD VFR DEPARTURE",
        "PF": "FLOW CONTROL PROCEDURE (RAD)",
        "PH": "HOLDING PROCEDURE",
        "PI": "IFR APPROACH PROCEDURE",
        "PK": "VFR APPROACH PROCEDURE",
        "PL": "FPL PROCESSING FILING & CONTINGENCY",
        "PM": "AERODROME OPERATION MINIMA",
        "PN": "NOISE OPERATING RESTRICTIONS",
        "PO": "OCA/OCH",
        "PR": "RADIO COMMUNICATION PROCEDURE",
        "PT": "TRANSITION ALTITUDE OR LEVEL",
        "PU": "MISSED APPROACH PROCEDURE",
        "PX": "MINIMUM HOLDING ALTITUDE",
        "PZ": "ADIZ PROCEDURE",
    },
    "RESTRICTIONS": {
        "RA": "AIRSPACE RESERVATION",
        "RD": "DANGER AREAS & TDA",
        "RO": "OVERFLYING OF & MIL ACFT SHALL AVOID",
        "RM": "MILITARY OPERATING AREA (TRA & TRAG)",
        "RP": "PROHIBITED AREA",
        "RR": "RESTRICTED AREA",
        "RT": "TEMPORARY RESTRICTED AREA & RA(T)",
    },
    "SERVICES": {
        "SA": "ATIS & DATIS",
        "SB": "ATS REPORTING OFFICE (ARO)",
        "SC": "AREA CONTROL CENTRE (ACC)",
        "SE": "FLIGHT INFORMATION SERVICE (EN-ROUTE) & LARS",
        "SF": "AD FLIGHT INFORMATION SERVICE (AFIS)",
        "SL": "FLOW CONTROL CENTRE",
        "SO": "OCEANIC AREA CONTROL CENTRE",
        "SP": "APPROACH CONTROL SERVICE",
        "SS": "FLIGHT SERVICE STATION",
        "ST": "TOWER",
        "SU": "UPPER AREA CONTROL CENTRE (UAC)",
        "SV": "VOLMET BROADCAST",
        "SY": "UPPER ADVISORY SERVICE",
    },
    "WARNINGS": {
        "WA": "AIR DISPLAY",
        "WB": "AEROBATICS",
        "WC": "CAPTIVE BALLOON & KITES",
        "WD": "DEMOLITION OF EXPLOSIVES",
        "WE": "EXERCISE",
        "WF": "AIR TO AIR REFUELLING",
        "WG": "GLIDING, PARAGLIDING, HANG GLIDING, PARAMOTOR",
        "WH": "BLASTING",
        "WJ": "BANNER, TARGET TOWING",
        "WL": "ASCENT OF FREE BALLOON",
        "WM": "MISSILE, GUN OR ROCKET FIRING",
        "WO": "LASER EMISSIONS & DISPLAYS",
        "WP": "PARACHUTE JUMPING (PJE)",
        "WR": "RADIOACTIVE MATERIALS, TOXIC CHEMICALS",
        "WS": "BURNING OR BLOWING GAS",
        "WT": "MASS MOVEMENT OF AIRCRAFT",
        "WU": "UNMANNED AIRCRAFT (UAS) & MODEL AIRCRAFT",
        "WV": "FORMATION FLIGHT (RED ARROWS)",
        "WW": "SIGNIFICANT VOLCANIC ACTIVITY",
        "WY": "AERIAL SURVEY",
        "WZ": "FIREWORKS",
    },
    "OTHER": {
        "OA": "AIS",
        "OB": "OBSTACLE",
        "OE": "AIRCRAFT ENTRY REQUIREMENT",
        "OL": "OBSTACLE LIGHTS",
        "OR": "RESCUE COORDINATION CENTRE",
        "XX": "PLAIN LANGUAGE",
    },
}

NOTAM_SUBJECTS = {}
for category, subjects in NOTAM_SUBJECT_CATEGORIES.items():
    for code, subject in subjects.items():
        NOTAM_SUBJECTS[code] = {
            "category": category,
            "description": subject,
        }
